blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://stackoverflow.com/questions/tagged/just-audio
    about: Ask a question on Stack Overflow (please use the just-audio tag).
